workspace:
  base: /usr/src/project
  path: .

pipeline:
  build:  # Build go app and package source files
    image: node
    commands:
        - npm run start
  image:  # Build image and publish to private registry
    image: plugins/docker
    repo: docker.io/sunjp123/node-drone
    secrets: [docker_name,docker_password]
    settings:
        username: docker_name
        password: docker_password
    dockerfile: ./cicd/Dockerfile
    default_tags: true
    commands:
        - docker login -p $DOCKER_PASWORD -u $DOCKER_NAME
    
