workspace:
  base: /usr/src/project
  path: .

pipeline:
  build:  # Build go app and package source files
    image: node
    commands:
        - npm run start
  publish:  # Build image and publish to private registry
    image: plugins/docker
    registry: http://registry.happyrecord.cn
    repo: registry.happyrecord.cn/sunjp123/node-drone
    #secrets: [ docker_username, docker_password ]
    dockerfile: ./cicd/Dockerfile
    default_tags: true
  deploy: 
    image: appleboy/drone-ssh
    host:
        happyrecord.cn
    username: root
    port: 22
    secrets: [ ssh_key ]
    command_timeout: 120s
    script:
        - cd /usr/src/project
        - /bin/bash run.sh
    
