workspace:
  base: /usr/src/project
  path: .

pipeline:
  build:  # Build go app and package source files
    image: node
    commands:
        - npm run start
  image:  # Build image and publish to private registry
    image: plugins/docker
    registry: hub.docker.com
    repo: sunjp123/node-drone
    settings:
        username: docker_name
        password: docker_password
    dockerfile: ./cicd/Dockerfile
    default_tags: true
    
