workspace:
  base: /usr/src/project
  path: .

pipeline:
  build:  # Build go app and package source files
    image: node
    commands:
        - npm run start
  image:  # Build image and publish to private registry
    image: plugins/docker
    repo: docker.io/sunjp123/node-drone
    secrets: [docker_name,docker_password]
    settings:
        username: sunjp123
        password: sunjianping88@
    dockerfile: ./cicd/Dockerfile
    default_tags: true
    
