workspace:
  base: /usr/src/project
  path: .

pipeline:
  build:  # Build go app and package source files
    image: node
    commands:
        - npm run start
  image:  # Build image and publish to private registry
    image: plugins/docker
    repo: sunjp123/test
    settings:
        username: sunjp123
        password: sunjianping88@
    context: ./cicd/
    dockerfile: ./cicd/Dockerfile
    default_tags: true
    
